sk1 = input("Ievadi skaitli 1:")
sk2 = input("Ievadi skaitli 2:")
print(type(sk1))
print(type(sk2))
print(f"Ievadītais skaitlis 1 ir {sk1}")
print(f"Ievadītais skaitlis 2 ir {sk2}")
print(f"Skaitļu summa ir {sk1 + sk2}")

sk1 = int(input("Ievadi skaitli 1:"))
sk2 = int(input("Ievadi skaitli 2:"))
print(type(sk1))
print(type(sk2))
print(f"Ievadītais skaitlis 1 ir {sk1}")
print(f"Ievadītais skaitlis 2 ir {sk2}")
print(f"Skaitļu summa ir {sk1 + sk2}")